<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        '/hook'
    ];

    public function handle($request, Closure $next)
    {
        if(in_array($request->path(),$this->except)){
            return $next($request);
        }else{
            return parent::handle($request, $next); // TODO: Change the autogenerated stub
        }

    }
}
